/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChangeOrder {
  'id' : bigint,
  'additionalCost' : number,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'createdBy' : Principal,
  'description' : string,
  'projectId' : bigint,
}
export interface MaterialPurchase {
  'id' : bigint,
  'supplier' : string,
  'item' : string,
  'totalCost' : number,
  'projectId' : bigint,
  'quantity' : number,
  'loggedBy' : Principal,
  'unitCost' : number,
}
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'clientName' : string,
  'name' : string,
  'createdBy' : Principal,
  'generalContractor' : string,
  'notes' : string,
  'projectValue' : number,
  'estimatedCompletionDate' : Time,
  'location' : string,
  'startDate' : Time,
}
export type ProjectStatus = { 'completed' : null } |
  { 'planned' : null } |
  { 'inProgress' : null };
export interface SafetyIncident {
  'id' : bigint,
  'description' : string,
  'reportedBy' : Principal,
  'projectId' : bigint,
  'timestamp' : Time,
}
export interface Task {
  'id' : bigint,
  'dueDate' : Time,
  'description' : string,
  'projectId' : bigint,
  'assignedCrew' : bigint,
  'isOutdoor' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMaterialPurchase' : ActorMethod<
    [bigint, string, number, number, string],
    bigint
  >,
  'addPermit' : ActorMethod<[bigint, string, string], bigint>,
  'addPhotoAnnotation' : ActorMethod<[bigint, string, bigint], undefined>,
  'approveChangeOrder' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCrewToTask' : ActorMethod<[bigint, bigint], undefined>,
  'checkIn' : ActorMethod<[bigint, string], undefined>,
  'createChangeOrder' : ActorMethod<[bigint, string, number], bigint>,
  'createProject' : ActorMethod<
    [string, string, string, string, number, string],
    bigint
  >,
  'flagOutdoorTasksForWeatherWarning' : ActorMethod<
    [bigint, string],
    undefined
  >,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMaterialPurchasesByProject' : ActorMethod<
    [bigint],
    Array<MaterialPurchase>
  >,
  'getPendingChangeOrders' : ActorMethod<[], Array<ChangeOrder>>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getSafetyIncidentsByProject' : ActorMethod<[bigint], Array<SafetyIncident>>,
  'getTasksByDueDate' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logMileage' : ActorMethod<[bigint, number, bigint], undefined>,
  'rejectChangeOrder' : ActorMethod<[bigint], undefined>,
  'reportSafetyIncident' : ActorMethod<[bigint, string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendSmartReminders' : ActorMethod<[], undefined>,
  'verifyCodeCompliance' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];