/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectStatus = IDL.Variant({
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'clientName' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'generalContractor' : IDL.Text,
  'notes' : IDL.Text,
  'projectValue' : IDL.Float64,
  'estimatedCompletionDate' : Time,
  'location' : IDL.Text,
  'startDate' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const MaterialPurchase = IDL.Record({
  'id' : IDL.Nat,
  'supplier' : IDL.Text,
  'item' : IDL.Text,
  'totalCost' : IDL.Float64,
  'projectId' : IDL.Nat,
  'quantity' : IDL.Float64,
  'loggedBy' : IDL.Principal,
  'unitCost' : IDL.Float64,
});
export const ChangeOrder = IDL.Record({
  'id' : IDL.Nat,
  'additionalCost' : IDL.Float64,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
});
export const SafetyIncident = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'reportedBy' : IDL.Principal,
  'projectId' : IDL.Nat,
  'timestamp' : Time,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'dueDate' : Time,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
  'assignedCrew' : IDL.Nat,
  'isOutdoor' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMaterialPurchase' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addPermit' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addPhotoAnnotation' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'approveChangeOrder' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCrewToTask' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'checkIn' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createChangeOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'flagOutdoorTasksForWeatherWarning' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMaterialPurchasesByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MaterialPurchase)],
      ['query'],
    ),
  'getPendingChangeOrders' : IDL.Func([], [IDL.Vec(ChangeOrder)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getSafetyIncidentsByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SafetyIncident)],
      ['query'],
    ),
  'getTasksByDueDate' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMileage' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Nat], [], []),
  'rejectChangeOrder' : IDL.Func([IDL.Nat], [], []),
  'reportSafetyIncident' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendSmartReminders' : IDL.Func([], [], []),
  'verifyCodeCompliance' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectStatus = IDL.Variant({
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'clientName' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'generalContractor' : IDL.Text,
    'notes' : IDL.Text,
    'projectValue' : IDL.Float64,
    'estimatedCompletionDate' : Time,
    'location' : IDL.Text,
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MaterialPurchase = IDL.Record({
    'id' : IDL.Nat,
    'supplier' : IDL.Text,
    'item' : IDL.Text,
    'totalCost' : IDL.Float64,
    'projectId' : IDL.Nat,
    'quantity' : IDL.Float64,
    'loggedBy' : IDL.Principal,
    'unitCost' : IDL.Float64,
  });
  const ChangeOrder = IDL.Record({
    'id' : IDL.Nat,
    'additionalCost' : IDL.Float64,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
  });
  const SafetyIncident = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'reportedBy' : IDL.Principal,
    'projectId' : IDL.Nat,
    'timestamp' : Time,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'dueDate' : Time,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
    'assignedCrew' : IDL.Nat,
    'isOutdoor' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMaterialPurchase' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addPermit' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addPhotoAnnotation' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'approveChangeOrder' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCrewToTask' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'checkIn' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createChangeOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'flagOutdoorTasksForWeatherWarning' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMaterialPurchasesByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MaterialPurchase)],
        ['query'],
      ),
    'getPendingChangeOrders' : IDL.Func([], [IDL.Vec(ChangeOrder)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getSafetyIncidentsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SafetyIncident)],
        ['query'],
      ),
    'getTasksByDueDate' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMileage' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Nat], [], []),
    'rejectChangeOrder' : IDL.Func([IDL.Nat], [], []),
    'reportSafetyIncident' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendSmartReminders' : IDL.Func([], [], []),
    'verifyCodeCompliance' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };